[2021.12.16/14:15:16] - Traceback (most recent call last):
  File "test.py", line 34, in <module>
    df, e=test()
  File "test.py", line 29, in test
    return df, e
UnboundLocalError: local variable 'df' referenced before assignment

[2021.12.16/14:15:50] - Traceback (most recent call last):
  File "test.py", line 36, in <module>
    if df=='':
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\core\generic.py", line 1443, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

